Add a component for handling meta tags project wide
thunderstore-io/thunderstore-ui pull request #537
Opened 2022-09-26 10:09 UTC by Oksamies

HeadWrapper component that is.

I fucked up with PR #534 so I needed to create a new PR.

refs TS-1077

2022-09-26 13:32 UTC, anttimaki commented on apps/sertra/README.md
> +When possible possible component in `HeadWrapper.tsx` should be used to add meta tags. This way the meta tag handling is centralized and can be edited easily for the whole site.
possible possible

2022-09-26 19:11 UTC, MythicManiac commented on apps/sertra/components/HeadWrapper.tsx
> +  title: string;
This is misleading and could easily be assumed to be user-visible title. `metaTitle` would be more fitting. Same for `description`, `metaDescription` would be more clear if you just see the call site.

2022-09-28 13:42 UTC, anttimaki requested changes

2022-09-28 13:42 UTC, anttimaki commented on apps/sertra/pages/create.tsx
> +        title="Submit Server"
You've changed the names of the props but haven't updated this and another place where the component is used.

2023-10-05 18:18 UTC, closed without merging