CS SB: Global css and variables changes
thunderstore-io/thunderstore-ui pull request #587
Opened 2022-12-19 15:26 UTC by Oksamies

Rename old globals.css to variables.css
Add globals.css with font defined in it

refs -

2022-12-20 01:24 UTC, MythicManiac requested changes
Do the move in one commit and then add the globals.css in a second one. Git won't be able to track the diffs nicely when they're in one commit and will likely lead to merge conflicts in other branches.

So make sure the diffs show a file being moved rather than deleted & another created

2022-12-20 11:38 UTC, VilppeRiskidev requested changes

2022-12-20 11:38 UTC, VilppeRiskidev commented on apps/cyberstorm-storybook/public/css/variables.css
> +a {
These `a` declarations would also go to the global.css

2022-12-20 11:40 UTC, VilppeRiskidev commented
The conversation here: https://discord.com/channels/877914952902516776/1054419542308290580/1054432263661703199 should be taken into consideration. I think the suggested separation makes sense and could be done in this PR.

2022-12-20 13:23 UTC, MythicManiac commented
I'd suggest doing the changes @VilppeRiskidev refers to in a follow-up PR / separate task to this one since the file move is quite disruptive to other work already and a good idea to get out of the way ASAP

2023-02-09 12:51 UTC, closed without merging

2023-02-09 12:51 UTC, VilppeRiskidev commented
Obsolete, this was done separately