Add option to have communities as landing page
thunderstore-io/thunderstore-ui pull request #822
Opened 2023-09-21 10:54 UTC by Oksamies

Dynamically use different landing page with the new env variable Redirect /communities to / when enabled

refs TS-1828

2023-09-21 11:32 UTC, anttimaki requested changes
Looks thorough, e.g. checking the footer and links which I forgot to mention in the task 👍🏻

2023-09-21 11:32 UTC, anttimaki commented on apps/cyberstorm-nextjs/.env.development
> +NEXT_PUBLIC_PRODUCTION_PAGE_STRUCTURE=
I second what Mythic mentioned in Discord, I think this is overkill.

2023-09-21 11:32 UTC, anttimaki commented on apps/cyberstorm-nextjs/middleware.ts
> +    if (request.nextUrl.pathname.startsWith("/communities")) {
This blocks the access to all subpages under `/communities`. Sure, we don't have them yet, but wouldn't hurt to use exact matching here either.

2023-09-26 06:24 UTC, anttimaki approved these changes
The changes are good but the commit message is now blatantly wrong. Feel free to merge without another review once that's fixed.

2023-09-26 11:29 UTC, Oksamies commented
Ah, nice catch, didn't even realize that

2023-09-27 13:32 UTC, merged